name: 'build pacprotocol (x86_64-linux-gnu)'
# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #- name: Install dependencies
      #  run: sudo apt-get update && sudo apt-get install -yq build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache
     
      # Runs a single command
      #- name: Build depends
      #  run: cd depends/ && make -j16 -l8

      - name: Refresh automake configs
        run: ./autogen.sh

      - name: Configure automake
        run: ./configure 
        
      - name: Build codebase
        run: make -j16 -l8

